joint_1_x: 0.0
joint_1_y: 0.0
joint_1_z: 0.0
joint_1_qx: 0.0
joint_1_qy: 0.0
joint_1_qz: 0.0
joint_1_qw: 1.0
joint_2_x: 0.0
joint_2_y: 0.0
joint_2_z: 0.0
joint_2_qx: 0.0
joint_2_qy: 0.0
joint_2_qz: 0.0
joint_2_qw: 1.0
joint_3_x: 0.0
joint_3_y: 0.0
joint_3_z: 0.0
joint_3_qx: 0.0
joint_3_qy: 0.0
joint_3_qz: 0.0
joint_3_qw: 1.0
joint_4_x: 0.0
joint_4_y: 0.0
joint_4_z: 0.0
joint_4_qx: 0.0
joint_4_qy: 0.0
joint_4_qz: 0.0
joint_4_qw: 1.0
joint_5_x: 0.0
joint_5_y: 0.0
joint_5_z: 0.0
joint_5_qx: 0.0
joint_5_qy: 0.0
joint_5_qz: 0.0
joint_5_qw: 1.0
joint_6_x: 0.0
joint_6_y: 0.0
joint_6_z: 0.0
joint_6_qx: 0.0
joint_6_qy: 0.0
joint_6_qz: 0.0
joint_6_qw: 1.0